### ISSUE TITLE
CPU hog issue with aiohttp client

### ISSUE THREAD

**Issue by philn** [beeware/gbulb#45] opened 2018-12-06 18:02 UTC
I don't know where the issue is exactly. In doubt I'm reporting here but it might actually be a bug in aiohttp.
The attached patch showcases the problem. Shortly after the download completed the CPU goes to 100%. Forever.

[aiohttp-gtk.diff.txt](https://github.com/nathan-hoad/gbulb/files/2654260/aiohttp-gtk.diff.txt)

**Comment by philn** [comment] 2019-01-08 22:59
@nathan-hoad ping?

**Comment by freakboy3742** [comment] 2024-05-04 03:37
Closing on the basis that I can't reproduce this problem any more - not sure if aiohttp has changed, or if an unrelated fix has addressed the problem.

**Closed by freakboy3742** 2024-05-04 03:37 UTC
Labels: bug
